### PR TITLE
Continue event sourcing implementation

### PR DESCRIPTION
**Pull request by tiagoamaro**
This PR is a continuation of the user event source example implementation.

While coding this, a couple of questions came up:

- (library) The `metadata` field almost serves as an extra annotation from developers? At their example, it seems they use for finding associations (e.g.: `metadata: { notification_id: 33456 }`)
- (database) Using Postgres' JSONB, we can safely remove the `serialize` methods from `app/models/lib/base_event.rb`
- (database) There's a strange scope called `recent_first` at the base event model. It seems they had MySQL limitations. This could disappear as well
- (commands) Default values for key arguments do not seem to exist. Could be a bit boring to fill them. Not sure if using kwargs for commands is a good idea. Probably hash arguments flexibility suites more in this case
    - This is clearly visible at this PR's controller, where dynamically setting keyword arguments will make any IDE (e.g. RubyMine) not understand where the key arguments are coming from, and assume that the method signature is wrong
- (note) If we rename events, we'll need to manually update all base event table `type`
    - This was described at the "Challenges" part of Kickstarter's article

### CODE REVIEW

**Comment by nickbrowne** [comment]
Yep, one of the things I was thinking about (considering some of the trouble kickstarter was having) was avoiding STI all together, and instead perhaps put the type in the `data` json column instead.

Then we could use `serialize` to serialize/deserialize the data column into the appropriate concrete class (or perhaps even just a plain old struct). This way if things got renamed you should be able to handle them with some code in the deserializer.

Not sure if it's a good idea or not, just something I was planning to experiment with at some point.

**Comment by nickbrowne** [comment]
Thanks for continuing with this Tiago, this will give us a lot more to play with!

**Comment by tiagoamaro** [comment]
@nickbrowne , I like your idea on putting the type on the serialized attribute! I think we could even use the `metadata` as a tool to store debugging/development information, such as "type" and other species of annotations. Since the `data` and `metadata` would be JSONB types, we could easily query those too!

Also, I would love to remove some meta magic on their approach. I'm not a big fan of this libs assumption and usage of keyword arguments and a couple of methods that doesn't seem to be used on the core library, but for their internal tooling (such as this one: https://github.com/nickbrowne/event_sourcing_users/blob/639f174f86daed5e74c8481c1920d36455009e36/app/models/lib/base_event.rb#L107-L109)

**Comment by nickbrowne** [comment]
Yup, totally agreed :+1:

**Pull request merged**
